### ISSUE TITLE
Book Crashing game when looking at the basic setup

### ISSUE THREAD

**Issue by almostsoloplayer** [baileyholl/Aura-Cascade#28]
everytime i look at the basic setup it crashes my game instantly goes to the shutting down internal servers and then it crashes

**Comment by LyraelRayne** [comment]
I am experiencing the same. using Build 593 on Forge 12.18.2075 (MC 1.9)

http://pastebin.com/JwMzRHax contains the fml-client-latest.log from when it crashed.

The relevant stack trace appears to be

 java.lang.AbstractMethodError: pixlepix.auracascade.lexicon.GuiLexiconEntry.renderToolTip(Lnet/minecraft/item/ItemStack;II)V
    at pixlepix.auracascade.lexicon.page.MultiblockPage.renderScreen(MultiblockPage.java:120)
    at pixlepix.auracascade.lexicon.GuiLexiconEntry.func_73863_a(GuiLexiconEntry.java:161)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:355)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1072)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
